DROP TABLE users;

CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL,
password VARCHAR(50),
email VARCHAR(50)
);


DROP TABLE tasks;

CREATE TABLE tasks(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId INT UNSIGNED,
parentTaskId INT UNSIGNED NULL,
description VARCHAR(700),
startTime DATETIME,
deadline DATETIME,
completed boolean,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (parentTaskId) REFERENCES tasks(id) ON DELETE CASCADE
);
